name: quikzi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  badges: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/bg.jpg
    - lib/assets/laptop.png
    - lib/assets/keyboard.png
    - lib/assets/headset.png
    - lib/assets/controller.png
    - lib/assets/mouse.png

